services:
    library:
        build:
            context: .
        env_file:
            - .env
        ports:
            - "8000:8000"
        volumes:
            - ./:/app
        command: >
            sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
        depends_on:
            - db

    db:
        image: postgres:17.5-alpine3.22
        restart: always
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - my_db:$PGDATA

volumes:
    my_db: